services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: srk
      POSTGRES_PASSWORD: ddlj
      PGDATA: /data/postgres
      POSTGRES_DB: amazon
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
  frontend:
    build: client/.
    ports:
      - "3000:3000"

  backend:
    build: server/.
    ports:
      - "5000:5000"
      - "5050:5050"
    depends_on:
      - postgres

volumes:
  database_data:
